# Generated by Django 4.0.1 on 2022-06-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pedidos_cantidadproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('nombreTitular', models.CharField(max_length=150, verbose_name='Nombre del titular')),
                ('numeroTarjeta', models.IntegerField(max_length=6, primary_key=True, serialize=False, verbose_name='Numero de la tarjeta')),
                ('ccvTarjeta', models.IntegerField(max_length=6, verbose_name='Ccv de la tarjeta')),
                ('fecha_ven', models.IntegerField(max_length=6, verbose_name='Fecha de vencimiento de la tarjeta')),
            ],
        ),
    ]
